# Generated by Django 3.0.5 on 2020-10-21 20:53

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='static/file/', validators=[app.validators.validate_file_extension])),
                ('directions', models.TextField()),
            ],
        ),
    ]
