# Generated by Django 3.0.5 on 2020-10-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_clear_name',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
