# Generated by Django 3.0.5 on 2020-10-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_file_file_clear_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_station', models.TextField()),
                ('year', models.TextField()),
                ('month', models.TextField()),
                ('day', models.TextField()),
                ('hours', models.TextField()),
                ('minutes', models.TextField()),
                ('seconds', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Some',
        ),
    ]
