# Generated by Django 3.0.5 on 2020-11-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201022_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='STATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_station', models.TextField()),
                ('id_session', models.TextField()),
                ('time', models.TextField()),
            ],
        ),
    ]
