# Generated by Django 3.0.5 on 2020-11-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUDIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_station', models.TextField()),
                ('id_session', models.TextField()),
                ('time_start', models.TextField()),
                ('time_end', models.TextField()),
                ('path_to_file', models.TextField()),
                ('time', models.TextField()),
            ],
        ),
    ]
